# Setup
title:        Cristian Darío Ortega Yubro
tagline:      A responsive theme for your project on GitHub Pages
baseurl:      ""
paginate:     1
locale:       "en"
theme:        jekyll-theme-cayman

# About/contact
author:
  name:       Cristian Darío Ortega Yubro
  url:        https://cristiandarioortegayubro.github.io 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown

theme: jekyll-theme-cayman
